apiVersion: v1
kind: Service
metadata:
    name: dreybrouckpipelinesjavascriptdocker
spec:
    type: LoadBalancer
    ports:
    - port: 80
    selector:
        app: dreybrouckpipelinesjavascriptdocker
